import { clearStyles, createElement, showHideElement } from '../src/clearStyles';
import { APP_NAME, DRAWER_ID } from './constants';
import styles from './styles/drawer.module.css';

/**
 * This adds a drawer that is used to display vital statistics
 *
 * api object is provided from Coviu platform when a plugin (AKA addon)
 * is activated and it provides methods that allow plugin to interact with
 * the call and other resources on coviu platform
 */
export default (api) => {
  const { h, thunk, DrawerToggle, Tooltip, DrawerHelp } = api.render;
  const { displayText } = api;

  return {
    id: DRAWER_ID,

    /**
     * Identifies the positioning of the drawer (left/right)
     */
    container: 'right',

    /**
     * Called to setup the drawer.
     * `drawerData` is an observable store that can be used to store drawer state information
     **/
    setup: (drawerData) => {
    },

    /**
     * This renders the drawer toggle (button)
     **/
    renderToggle: (drawerState, active) => {
      return thunk(`${DRAWER_ID}_toggle`, { drawerState, active }, () => {
        return DrawerToggle(
          DRAWER_ID,
          {
            notify: 1,
            label: displayText(APP_NAME),
            open: active === DRAWER_ID,
            className: styles.DrawerToggle,
          },
          () => {
            if (active !== DRAWER_ID) {
              clearStyles(DRAWER_ID);
              createElement();
              showHideElement(DRAWER_ID, true);
            } else {
              showHideElement(DRAWER_ID, false);
            }
          }
        );
      });
    },

    /**
     * Renders the drawer
     **/
    renderDrawer: (drawerState, active) => {
      return thunk(DRAWER_ID, { drawerState }, () => {
        const {
          counter,
          calculations,
          participantState,
          webhookResponse,
        } = drawerState;
        console.log('drawer State => ', drawerState);
        return h('div.Drawer_Content', [
          h('div.Drawer_Title', displayText('Drawer Title')),
          DrawerHelp('About this drawer', [
            'You can add all sorts of elements here - premade components, as well as custom ones',
          ]),
          h(`div.${styles.card}`, [
            h(
              'button.Button',
              {
                'ev-click': () => counterState.set(counter + 1),
              },
              'Increment'
            ),
            h(`p`, `Current count: ${counter}`),
          ]),
          h(`div.${styles.card}`, [
            h('h3', 'Calculation from Guest:'),
            h(
              'div',
              calculations !== 'undefined'
                ? calculations.map((calc) => {
                    return h(
                      `p`,
                      `Input: ${calc.input}, Output: ${calc.output}`
                    );
                  })
                : 'no calculations generated by call guest to dipslay'
            ),
          ]),
          h(`div.${styles.card}`, [
            h(
              'button.Button',
              {
                'ev-click': () => {
                  getParticipants();
                },
              },
              'Display call participants'
            ),
            h(
              'div',
              participantState !== 'undefined'
                ? participantState.map((participant, i) => {
                    return h(
                      'div',
                      `Participant ${i + 1}: ${participant.displayName}`
                    );
                  })
                : 'no participants to display , click display participants button to show current participants'
            ),
          ]),
          h(`div.${styles.card}`, [
            DrawerHelp('WebHooks', [
              h(
                'p',
                `as an external dev in order to test webhooks, You would need to raise a ticket on link below for Coviu dev team to add webhook config as shown in documentaion and sample code`
              ),
              h(
                'a.Link.-underline.-pleasant',
                {
                  href:
                    'https://coviu.atlassian.net/servicedesk/customer/portal/8/group/13/create/10120',
                  target: '_blank',
                },
                displayText('webhook register request')
              ),
            ]),
            h(
              'button.Button',
              { 'ev-click': () => triggerWebhook() },
              'Call webhook api'
            ),
            h('p', webhookResponse),
          ]),
        ]);
      });
    },
  };
};
